### ISSUE TITLE
[Question] sample using ffmpeg 

### ISSUE THREAD

**Issue by r8code** [membraneframework/membrane_demo#21]
Hi , 
First I want to thank you for making this great library ,
I want ask is there any example using ffmpeg instead of gstreamer for rtp_to_hls example ?
Thank you

**Comment by mat-hek** [comment]
Hi @r8code, glad you liked membrane ;) For FFmpeg things are more complicated in this case. Streaming video can be done with
```
ffmpeg -re -f lavfi -i testsrc=s=320x240:r=30,format=yuv420p \
-f rtp -sdp_file out.sdp -vcodec h264 -profile:v baseline -flags +global_header rtp://127.0.0.1:5000
```
but you'll need to extract the `sprop-parameter-sets` field from the generated `sdp.out` file. It'll look like
`Z0LADdkBQfsBEAAAAwAQAAADA8DxQqSA,aMuDyyA=`
The part before the comma is SPS, and the one after the comma is PPS, both encoded in base64. You need to decode both, prefix with h264 frame prefix (`<<0, 0, 0, 1>>`) and pass as sps and pps options to `Membrane.Element.FFmpeg.H264.Parser`.

The process can be automated with help of https://hexdocs.pm/membrane_protocol_sdp

Streaming both audio and video could be achieved with

```
ffmpeg -re -f lavfi -i testsrc=s=320x240:r=30,format=yuv420p -f lavfi -i sine=f=440:b=4 -shortest \
-f rtp -sdp_file out.sdp -an -vcodec h264 -profile:v baseline -flags +global_header rtp://127.0.0.1:5000 \
-f rtp -payload_type 127 -vn -acodec aac rtp://127.0.0.1:5000
```

unfortunately, that won't work currently, because https://hexdocs.pm/membrane_rtp_aac_plugin/ doesn't support all the features of RTP AAC payload yet, while FFmpeg happens to use some unsupported fields and it can't be configured not to do so afaik.

**Comment by r8code** [comment]
Wow, thanks for the guides , it's good for now since video is the primary needed ,
I'll try again with gstreamer since I'm stuck with  no element faac ,
Thank you
