### ISSUE TITLE
rtp_to_hls demo  high CPU usage.

### ISSUE THREAD

**Issue by ChungTak** [membraneframework/membrane_demo#22]
rtp_to_hls demo  CPU usage is so high, beam process uses 120%.  it just  one rtp  stream ->  hls .

Is there any optimization method ?

test cmmand:
`gst-launch-1.0 -v audiotestsrc ! audio/x-raw,rate=44100 ! faac ! rtpmp4gpay  pt=127 ! udpsink host=127.0.0.1 port=5000 \
    videotestsrc ! video/x-raw,format=I420 ! x264enc key-int-max=10 tune=zerolatency ! rtph264pay pt=96 ! udpsink host=127.0.0.1 port=5000`

Erlang/OTP 22.3
Elixir (1.10.4)
SYSTEM: Mac OS 10.15.3
CPU: 1.99 GHz Intel 4 Core i7
RAM: 16 GB 2400 MHz DDR4

**Comment by mat-hek** [comment]
Hi @ChungTak ,

thanks for catching that. Since we got ~15% on a similar setup when streaming from our IOs app, I supposed it can be related to the streaming engine. So I checked how that behaves with FFmpeg, as described [here](https://github.com/membraneframework/membrane_demo/issues/21#issuecomment-678973638), and got ~15% CPU use. Some other facts I found out:
- increasing resolution to HD when streaming via FFmpeg almost doesn't affect CPU use
- streaming GStreamer's test video with FFmpeg gives similar results
- streaming GStreamer's test video encoded in GStreamer with FFmpeg without transcoding increases CPU use ~3 times
- GStreamer produces way more UDP packets when streaming the same video, what can be seen in Wireshark

So the conclusion is, GStreamer encodes and packetizes the stream in a way that generates lot's of RTP packets, and that makes membrane use more CPU. I'm still unsure why _that_ much more, we're going to profile the case when focusing on optimisation again, what can be tracked [here](https://github.com/membraneframework/membrane_core/issues/243).

For now, you can try:
- using [UDP source from group-packets branch](https://github.com/membraneframework/membrane-element-udp/tree/group-packets) and setting `packets_per_buffer` option, so that packets were grouped on the initial steps of processing, limiting the number of sent messages
- applying some encoding and RTP packetization options of GStreamer
- using something else to generate the stream

**Comment by arruah** [comment]
I got this error when trying to do mix run

**Comment by ChungTak** [comment]
Ubuntu : sudo apt-get install portaudio19-dev
Mac:  brew install portaudio
Centos7: sudo yum install -y portaudio-devel

**Comment by arruah** [comment]
also sudo apt install libmad0-dev
