### ISSUE TITLE
Muting local camera/microphone does not stop sending media via MediaTrack

### ISSUE THREAD

**Issue by Qizot** [membraneframework/membrane_demo#54]
When user using Videoroom decides to mute microphone/camera he is still sending media to the server, therefore generating traffic and SFU load.

**Comment by mickel8** [comment]
Setting `MediaStreamTrack.enabled` to `false` will cause sending blackness for video tracks and silence for audio tracks so indeed our server will be still receiving data. 

I think we are doing it properly as in docs there is `This can be used to intentionally mute a track.` and in other place `Note: You can implement standard "mute" functionality by setting enabled to false. The muted property refers to a condition in which there's no media because of a technical issue.`

https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/enabled

**Comment by Qizot** [comment]
Yup, this is a problem as the blackness will still be sent with the same framerate as the video (in our case it is 30 fps, should be lowered by the way). 

Replacing video track with fake canvas track should do the job as it does not send any packets whatsoever.
